### ISSUE TITLE
歌词滚动动画效果

### ISSUE THREAD

**Issue by ti-xian-mu-ou** [IFmiss/vue-website#11]
https://github.com/IFmiss/vue-website/blob/eea07689a62937273d8e20fff147b043af5293cd/src/components/music/music.js#L194
这里可以用css3的transition属性实现滚动效果；还可以实现当前歌词的高亮；都可以不使用jQuery

**Comment by IFmiss** [comment]
@ti-xian-mu-ou 感谢提议

**Comment by ti-xian-mu-ou** [comment]
楼主可以实现账号关联网易云音乐账号吗？这样对网易云音乐的个性化东西就很多了
