### ISSUE TITLE
第一次打开的时候无论你点的是第几个图片显示的都是第一张图片问题解决

### ISSUE THREAD

**Issue by yuanker** [IFmiss/vue-website#13]
楼主网站做的很棒哦，很简洁，本人是做后台语言开发的，一直想做一个博客，最近在研究前端方面的东西，准备参考一下你的代码也入手vue做一个个人博客，源码看到楼主说个人状态页的图片在swiper上预览的时候，第一次打开的时候无论你点的是第几个图片显示的都是第一张图片，报错显示Cannot read property 'swiper' of undefined，看了下原因，原因是这个swiper的父母有v-if，将v-if更改为v-show就好了哦
<swiper :options="swiperOption" ref="mySwiper" v-show="picListInfo.detail && globalInfo.contentInfo">

**Comment by IFmiss** [comment]
高手！我试了下解决了
