### ISSUE TITLE
已解决：项目打包时候的问题  主要是静态资源获取的问题，配置内容见 https://github.com/IFmiss/vue-website/blob/master/config/index.js#L4

### ISSUE THREAD

**Issue by FirstTree** [IFmiss/vue-website#6]
// assetsRoot: path.resolve(__dirname, '../dist/new'),
    // assetsSubDirectory: 'static',
    // assetsPublicPath: 'new/',
    // Paths
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    productionSourceMap: true,

**Comment by IFmiss** [comment]
@FirstTree  我用了你这个方式  这个是放在根目录下   静态资源文件为 static的目录   首页为index.html
我稍微改了下

assetsRoot: path.resolve(__dirname, '../dist'),
assetsSubDirectory: 'new',
assetsPublicPath: '/',
productionSourceMap: true,

就可以了
感谢！
