### ISSUE TITLE
你好，请问播放音乐的时候，背景虚化是哪个js文件？谢谢了

### ISSUE THREAD

**Issue by ShenGunNiTian** [IFmiss/vue-website#8]

**Comment by IFmiss** [comment]
背景虚化是music/music.vue下的一个元素
![image](https://user-images.githubusercontent.com/17402583/40878325-ed120066-66c1-11e8-83bb-e0bf11115b90.png)
是根据音乐封面来的，只是加了
![image](https://user-images.githubusercontent.com/17402583/40878330-fddfea8e-66c1-11e8-9d9a-25436f9db546.png)
